### PR TITLE
Semantic UI

### PR DESCRIPTION
**Pull request by BigBlueHat**
Made it purty. :smile_cat: 

However, the variable names could use some updating...they're no longer accurate (`dl`, `ul`, etc aren't what they used to be...).

Let me know if you want another PR that improves that. Also happy to spread this love across the other clients. :smile: 

:tophat:

### CODE REVIEW

**Comment by mamund** [comment]
yes, cleaning up the var names is a good idea. i might use `d1`, `d2` or even something more meaning full (`dList`, `dItem`, etc.)?  nothing too long or complicated, tho.

once you do that, we can merge this in and give it several test runs.

BTW - love that you're adding your soundtrack!!!!!

**Comment by BigBlueHat** [comment]
@mamund names updated!

Thanks for not minding the sound track add. :wink: Seemed to be a requirement. :grinning:

**Comment by mamund** [comment]
@BigBlueHat 

sound track is a MUST for this project!

you want me to do the merge or you?

**Comment by BigBlueHat** [comment]
@mamund my one concern is that I've made some changes to `dom-help.js` and that's used by the other clients...which I've not tested thoroughly.

If you're happy with this route, though, I think it makes sense to merge it and fix/update the others to match--or at least not break...--this variation.

:thought_balloon: :grey_question:

**Comment by mamund** [comment]
Bah!

Copy the old dom-help.js to a new name and patch  the other clients. Then
you can never and start new branches for the other clients.

Cool?

**Comment by BigBlueHat** [comment]
Actually, the change vector is minimal:
https://github.com/RESTFest/ndcoslo2015/pull/2/files#diff-2

Only the additional class names _may_ effect the other clients...and that seems unlikely...or easily resolvable. Given that we're moving this way anyhow, I say soldier on! Merging shortly. :watch:

**Pull request merged**
